---
inherit_gem:
  voxpupuli-test: rubocop.yml
#
AllCops:
  Include:
    - '**/*.rb'
    - 'Rakefile'
  Exclude:
    - '!Rakefile'
    - 'spec/fixtures/**/*'
#
Naming/FileName:
  Exclude:
    - Rakefile
...
